server:
  port: 8081
packages:
  action: com.eding.example

database:
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=Hongkong
  username: root
  password: root
  driverClassName: com.mysql.cj.jdbc.Driver
  connectionTimeout: 30000
  idleTimeout: 60000
  maxLifetime: 600000
  minimumIdle: 10
  maximumPoolSize: 65
  poolName: TxnDatabasePool
  leakDetectionThreshold: 5000
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048